### ISSUE TITLE
Unable to use common features of ECMA 262 Regular Expressions with regex validation

### ISSUE THREAD

**Issue by jalvinake** [amazon-ion/ion-schema-kotlin#181]
The [Ion schema doc](https://amzn.github.io/ion-schema/docs/spec.html#regex) states that I can use a string that forms to [ECMA 262 Regular expressions](https://262.ecma-international.org/5.1/#sec-7.8.5), but I am unable to use pretty standard features of that spec. The biggest issue I ran into was the inability to use escaped characters in a codepoint class. Examples:

- validating a char is alphabetic OR whitespace [a-z\s])
- validating a char is not a special character that browsers have difficulty with [^\\\/]

This is due to additional checks done by the Ion validator here: https://github.com/amzn/ion-schema-kotlin/blame/d4dc796d97684fa78adb0ba4ec21b9a04dc41967/src/com/amazon/ionschema/internal/constraint/Regex.kt#L133

There are additional limitations posed that are supported in ECMA 262, so I am wondering if instead of limiting the regex, the library could just defer to the validations built-in to the kotlin regex parsers.

**Comment by popematt** [comment]
Thanks for bringing this up.

It sounds like there are actually three different (but related) problems/questions here.
1. ISL does not allow predefined character classes inside a _RegularExpressionClass_
2. ISL does not allow most special characters to be escaped in a _RegularExpressionClass_
3. Why does `ion-schema-kotlin` have these extra validations for Regular Expressions at all, and can we get rid of them in favor of Kotlin's `Regex`?

__Predefined Classes inside other Regular Expression Classes__
Example:
> validating a char is alphabetic OR whitespace [a-z\s]

I dug into the ECMA specification and was able to confirm that the evaluation of character class allows it to be a [union of multiple character classes](https://262.ecma-international.org/5.1/#sec-15.10.2.15), so I can't see any reason not to allow predefined character classes to be used inside a character class. However, this will require an update to the Ion Schema specification to allow this sort of character class before we can make any change to the implementation, since the Ion Schema Spec does specifically limit the features of ECMA 262. As a temporary workaround, you can substitute `[a-z\s]` with `([a-z]|\s)`, but this approach doesn't work for a negated character class, such as `[^\s\d]` because ISL does not support negative lookahead.


__Escaping Special Characters inside Regular Expression Classes__
Example:
> validating a char is not a special character that browsers have difficulty with [^\\\/]

It is not required to escape `/` in a regular expression, so you can replace `[^\\\/]` with `[^\\/]`, and this is actually true of most special characters. (Do note, though, that in Ion/ISL, because `\` must be escaped, `[^\\/]` would be written as `regex: "[^\\\\/]"`.)

I've pulled together a few specific grammar elements, found in [Annex A.1](https://262.ecma-international.org/5.1/#sec-A.1) of the ECMA spec.

```
RegularExpressionClassChar ::
    RegularExpressionNonTerminator but not one of ] or \
    RegularExpressionBackslashSequence

RegularExpressionNonTerminator ::
    SourceCharacter but not LineTerminator

SourceCharacter ::
    any Unicode code unit
```

If we apply some substitutions, it becomes:

```
RegularExpressionClassChar ::
    any Unicode code unit but not LineTerminator or ] or \
    RegularExpressionBackslashSequence
```

So, according to ECMA-262, the only special characters that need to be escaped in a character class are `\` and `]`  or any line terminator (all of which are allowed by `ion-schema-kotlin` already).

__Regarding `ion-schema-kotlin`'s Regex Validations__
> could [the library] just defer to the validations built-in to the kotlin regex parsers

In the KDoc for `Regex` constraint, we have the rationale for performing additional parsing on the regex string.
https://github.com/amzn/ion-schema-kotlin/blob/d4dc796d97684fa78adb0ba4ec21b9a04dc41967/src/com/amazon/ionschema/internal/constraint/Regex.kt#L27-L31
This is important because we don't want someone to inadvertently create a schema with a Regex that is not portable between Ion Schema implementations. In other words, a schema should be equally valid and have the same functionality whether used with `ion-schema-kotlin`, `ion-schema-rust`, or some future implementation of Ion Schema. For JVM, Kotlin's [`Regex` is backed by `java.util.regex.Pattern`](https://github.com/JetBrains/kotlin/blob/master/libraries/stdlib/jvm/src/kotlin/text/regex/Regex.kt#L85), so using `Regex` has the same concerns as using `Pattern`.

----

I've created an issue https://github.com/amzn/ion-schema/issues/54 to look into whether we can add more Regex features and either update the spec or explain why we cannot support those features.
